@WebAPI_HostAddress = http://localhost:5299



###
POST {{WebAPI_HostAddress}}/users
Content-Type: application/json
Accept: application/json

{
    "userName": "newUser123",
    "password": "securePassword!"
}
###
POST {{WebAPI_HostAddress}}/users
Content-Type: application/json
Accept: application/json

{
    "userName": "newUser1234",
    "password": "securePassword!!"
}
###
PATCH {{WebAPI_HostAddress}}/users/2
Content-Type: application/json
Accept: application/json

{
    "newUserName": "updatedUser1234",
    "newPassword": "newSecurePassword!",
    "OldUserName": "newUser123",
    "OldPassword": "securePassword!"
}
###
DELETE {{WebAPI_HostAddress}}/users/1
Accept: application/json
###
GET {{WebAPI_HostAddress}}/users
Accept: application/json
###
GET {{WebAPI_HostAddress}}/users?usernameContains=new
Accept: application/json
###
GET {{WebAPI_HostAddress}}/users/2
Accept: application/json